name = "sk-trade-pattern"
main = "dist/index.html"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "./dist"
entry-point = "workers-site"

[env.production]
name = "pattern-analyzer-prod"

[env.staging]
name = "pattern-analyzer-staging"

[build]
command = "npm run build"
watch_dir = "src"

[[routes]]
pattern = "/*"
script_name = "workers-site"
zone_name = "your-domain.com"  # Replace with your actual domain

[triggers]
crons = []
